name: markdown_editor
description: A Repository for a rich text markdown editor
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  url_launcher: ^6.1.14
  mocktail: ^1.0.1
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  bloc: ^8.1.0
  image_picker: ^1.0.2
  permission_handler: ^11.0.1
  flutter_bloc: ^8.1.2
  ui_components:
    path: ../ui_components
  file_picker: ^6.0.0
  flutter_sound: ^9.2.13
  learning_app:
    path: ../../
  audioplayers: ^5.0.0
  path_provider: ^2.0.14
  flutter_math_fork: ^0.7.1

dependencies:
  equatable: ^2.0.5
  material: ^1.0.0+2
