name: markdown_editor
description: A Repository for a rich text markdown editor
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  bloc: ^8.1.0
  image_picker: ^0.8.7
  flutter_sound_lite: ^8.5.0
  permission_handler: ^10.2.0
  flutter_bloc: ^8.1.2
  ui_components:
    path: ../ui_components
  file_picker: ^5.3.2

  learning_app:
    path: ../../
  audioplayers: ^4.1.0
  path_provider: ^2.0.14
  flutter_math_fork: ^0.7.1

dependencies:
  equatable: ^2.0.5
  material: ^1.0.0+2
