name: hive_cards_api
description: A Flutter implementation of the CardsApi that uses the hive database.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  cards_api:
    path: ../cards_api
  markdown_editor:
    path: ../markdown_editor
  rxdart: ^0.27.5
