name: cards_repository
description: A Repository that handles everything related to cards, subjects and groups
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cards_api:
    path: ../cards_api
  markdown_editor:
    path: ../markdown_editor
dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  hive_flutter: ^1.1.0
