name: learning_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  path_provider: ^2.0.14
  cards_api:
    path: packages/cards_api
  hive_cards_api:
    path: packages/hive_cards_api
  cards_repository:
    path: packages/cards_repository
  ui_components:
    path: packages/ui_components
  markdown_editor:
    path: packages/markdown_editor
  uuid: ^3.0.7
  dynamic_color: ^1.5.4
  google_fonts: ^4.0.4
  characters: ^1.2.1
  flutter_colorpicker: ^1.0.3
  flutter_animate: ^4.1.1+1
  image_picker: ^0.8.7
  flutter_sound_lite: ^8.5.0
  permission_handler: ^10.2.0
  audioplayers: ^4.1.0
  file_picker: ^5.3.2
  flutter_math_fork: ^0.7.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
