name: ui_components
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  flutter_colorpicker: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  flutter_svg: ^2.0.7




dependencies:
  flutter_animate: ^4.1.1+1
  material: ^1.0.0+2

