// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2Cr95z_rgWdUi23J9AGRQ3D2-gXRDp0',
    appId: '1:785115241499:web:106497c0c7130677552cbe',
    messagingSenderId: '785115241499',
    projectId: 'learningapp-c60b3',
    authDomain: 'learningapp-c60b3.firebaseapp.com',
    storageBucket: 'learningapp-c60b3.firebasestorage.app',
    measurementId: 'G-XY0DNXXBJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGw-DY_qNabWUHt7-LJ65CuRMmfQohyIQ',
    appId: '1:785115241499:android:b31a1c1d8d15f7ea552cbe',
    messagingSenderId: '785115241499',
    projectId: 'learningapp-c60b3',
    storageBucket: 'learningapp-c60b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICFBePmEt4JRLtc5Il_XF9YA-rM9piUY',
    appId: '1:785115241499:ios:485765ad595d87f5552cbe',
    messagingSenderId: '785115241499',
    projectId: 'learningapp-c60b3',
    storageBucket: 'learningapp-c60b3.firebasestorage.app',
    iosBundleId: 'com.example.learningAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDICFBePmEt4JRLtc5Il_XF9YA-rM9piUY',
    appId: '1:785115241499:ios:485765ad595d87f5552cbe',
    messagingSenderId: '785115241499',
    projectId: 'learningapp-c60b3',
    storageBucket: 'learningapp-c60b3.firebasestorage.app',
    iosBundleId: 'com.example.learningAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN2Cr95z_rgWdUi23J9AGRQ3D2-gXRDp0',
    appId: '1:785115241499:web:5269e77c35a36862552cbe',
    messagingSenderId: '785115241499',
    projectId: 'learningapp-c60b3',
    authDomain: 'learningapp-c60b3.firebaseapp.com',
    storageBucket: 'learningapp-c60b3.firebasestorage.app',
    measurementId: 'G-7VCLTZ1LL2',
  );
}
