import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF526600),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFD3EE7F),
  onPrimaryContainer: Color(0xFF171E00),
  secondary: Color(0xFF5B6146),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE0E6C4),
  onSecondaryContainer: Color(0xFF191E08),
  tertiary: Color(0xFF3A665E),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFBCECE1),
  onTertiaryContainer: Color(0xFF00201B),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFEFCF4),
  onBackground: Color(0xFF1B1C17),
  surface: Color(0xFFFEFCF4),
  onSurface: Color(0xFF1B1C17),
  surfaceVariant: Color(0xFFE3E4D3),
  onSurfaceVariant: Color(0xFF46483C),
  outline: Color(0xFF76786B),
  onInverseSurface: Color(0xFFF3F1E9),
  inverseSurface: Color(0xFF30312B),
  inversePrimary: Color(0xFFB8D166),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF526600),
  outlineVariant: Color(0xFFC7C8B8),
  scrim: Color(0xFF000000),
);
const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF44D8F1),
  primaryContainer: Color(0xFF004E59),
  secondary: Color(0xFFB1CBD1),
  secondaryContainer: Color(0xFF334A50),
  surface: Color.fromARGB(255, 28, 30, 32),
  background: Color.fromARGB(255, 28, 30, 32),
  error: Color(0xFFFFB4AB),
  onPrimary: Color(0xFF00363E),
  onSecondary: Color(0xFF1C3439),
  onBackground: Color.fromARGB(255, 237, 238, 248),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFB4AB),
  onInverseSurface: Color(0xFF2E3132),
  onPrimaryContainer: Color(0xFFA1EFFF),
  onSecondaryContainer: Color(0xFFCDE7ED),
  onSurface: Color(0xFFFFFFFF),
  onSurfaceVariant: Color(0xFFBFC8CA),
  onTertiary: Color(0xFF262F4D),
  onTertiaryContainer: Color(0xFFDBE1FF),
  outline: Color(0xFFE3E5E6),
  outlineVariant: Color(0xFF3F484A),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF44D8F1),
  surfaceVariant: Color(0xFF3F484A),
  tertiary: Color(0xFFBCC5EB),
  tertiaryContainer: Color(0xFF3C4665),
  inversePrimary: Color(0xFF006876),
  inverseSurface: Color(0xFFE1E3E3),
);

// const darkBlackAndWhiteColorScheme = ColorScheme(
//   brightness: Brightness.dark,
//   primary: Colors.black87,
//   onPrimary: Colors.white,
//   primaryContainer: Colors.black54,
//   onPrimaryContainer: Colors.white,
//   secondary: Colors.black45,
//   onSecondary: Colors.white,
//   secondaryContainer: Color(0xFF444930),
//   onSecondaryContainer: Color(0xFFE0E6C4),
//   tertiary: Color(0xFFA1D0C5),
//   onTertiary: Color(0xFF033730),
//   tertiaryContainer: Colors.black87,
//   onTertiaryContainer: Colors.white,
//   error: Color(0xFFFFB4AB),
//   errorContainer: Color(0xFF93000A),
//   onError: Color(0xFF690005),
//   onErrorContainer: Color(0xFFFFDAD6),
//   background: Colors.black87,
//   onBackground: Colors.white,
//   surface: Color(0xFF1B1C17),
//   onSurface: Color(0xFFE4E3DA),
//   surfaceVariant: Colors.black87,
//   onSurfaceVariant: Colors.white,
//   outline: Color(0xFF909283),
//   onInverseSurface: Color(0xFF1B1C17),
//   inverseSurface: Color(0xFFE4E3DA),
//   inversePrimary: Color(0xFF526600),
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFFB8D166),
//   outlineVariant: Color(0xFF46483C),
//   scrim: Color(0xFF000000),
// );

// const lightBlackAndWhiteColorScheme = ColorScheme(
//   brightness: Brightness.light,
//   primary: Colors.white,
//   onPrimary: Colors.black,
//   primaryContainer: Colors.white,
//   onPrimaryContainer: Colors.black,
//   secondary: Colors.white70,
//   onSecondary: Colors.black,
//   secondaryContainer: Color(0xFFE8E8E8),
//   onSecondaryContainer: Colors.black,
//   tertiary: Color(0xFFE0E6C4),
//   onTertiary: Colors.black,
//   tertiaryContainer: Colors.white,
//   onTertiaryContainer: Colors.black,
//   error: Color(0xFFB00020),
//   errorContainer: Color(0xFFFFEBEE),
//   onError: Color(0xFFB00020),
//   onErrorContainer: Color(0xFFFFEBEE),
//   background: Colors.white,
//   onBackground: Colors.black,
//   surface: Color(0xFFF5F5F5),
//   onSurface: Colors.black,
//   surfaceVariant: Colors.white,
//   onSurfaceVariant: Colors.black,
//   outline: Color(0xFFC4C4C4),
//   onInverseSurface: Colors.white,
//   inverseSurface: Colors.black,
//   inversePrimary: Colors.black,
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFFB8D166),
//   outlineVariant: Color(0xFF9E9E9E),
//   scrim: Color(0x99000000),
// );

final List<Color> defaultColors = [
  Colors.redAccent[100]!,
  Colors.orangeAccent[100]!,
  Colors.yellowAccent[100]!,
  Colors.greenAccent[100]!,
  Colors.blueAccent[100]!,
  Colors.deepPurpleAccent[100]!,
];
