name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v1

      # Setup Java environment for Android build
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

        # Get the tag name
      - name: Get Tag
        id: get_tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Setup the Flutter environment
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "3.19.6"

      # Get Flutter dependencies
      - run: flutter pub get

      # Build APK for production
      - name: Build prod APK
        run: flutter build apk --release

      # Upload the generated APKs to artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: staging-release-apk
          path: build/app/outputs/apk/release/app-release.apk

      # Create a release and upload the APK for staging
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          draft: false
          prerelease: false
